---
- name: Ensure SSH public keys are present for each user
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.public_key_path) }}"
  with_items: "{{ users }}"
